export const LABELS = {
  en: {
    formTitle: "Form",
    name: "Your Name",
    introName: "Name of the person who referred you in this group",
    phoneNumber: "Your Phone Number",
    archanaiName: "Name of the person for whom Archanai is to be done",
    archanaiPhoneNumber:
      "Contact Number of a person for whom Archanai is to be done",
    archanaiDOB: "Birth month of a person for whom Archanai is to be done",
    archanaiStar: "Birth Nakshatra of a person for whom Archanai is to be done",
    archanaiDetails:
      "Gothram/Kulam/Koottam of a person for whom Archanai is to be done",
    email: "Email",
    address: "Postal address for sending Abhisheka Prasadam",
    submit: "Submit",
    donation: "Donation amount",
    switchLabel: "Switch to Tamil",
    addressForsendingDoantion: "Address for sending donation",
    transactionDetails: "Transaction ID Details",
    comments: "For Any other comments, contact Dhanabal Othuvar",
  },
  ta: {
    formTitle: "படிவம்",
    name: "தங்களின் பெயர்",
    introName: "இந்த குழுவிற்கு தங்களை அறிமுகப்படுத்தியவரின் பெயர்",
    phoneNumber: "தங்களின் அலைபேசி எண்",
    archanaiName: "அர்ச்சனை செய்பவரின் பெயர்",
    archanaiPhoneNumber: "அர்ச்சனை செய்பவரின் அலைபேசி எண்",
    archanaiStar: "அர்ச்சனை செய்பவரின் பிறந்த நட்சத்திரம்",
    archanaiDOB: "அர்ச்சனை செய்பவரின் பிறந்த மாதம்",
    archanaiDetails: "அர்ச்சனை செய்பவரின் கோத்திரம் / குலம் / கூட்டம்",
    address: "அபிஷேக பிரசாதம் அனுப்ப வேண்டிய முகவரி",
    email: "மின்னஞ்சல்",
    submit: "சமர்ப்பிக்கவும்",
    donation: "நன்கொடை தொகை",
    addressForsendingDoantion: "பணம் அனுப்பும் முகவரி",
    switchLabel: "ஆங்கிலத்திற்கு மாறுக",
    transactionDetails: "பணம் அனுப்பிய விபரம்",
    comments: "மற்ற தகவல்களுக்கு தனபால் ஓதுவார்",
  },
};
export const TAMIL_MONTH = [
  { label: "சித்திரை", value: "சித்திரை" },
  { label: "வைகாசி", value: "வைகாசி" },
  { label: "ஆனி", value: "ஆனி" },
  { label: "ஆடி", value: "ஆடி" },
  { label: "ஆவணி", value: "ஆவணி" },
  { label: "புரட்டாசி", value: "புரட்டாசி" },
  { label: "ஐப்பசி", value: "ஐப்பசி" },
  { label: "கார்த்திகை", value: "கார்த்திகை" },
  { label: "மார்கழி", value: "மார்கழி" },
  { label: "தை", value: "தை" },
  { label: "மாசி", value: "மாசி" },
  { label: "பங்குனி", value: "பங்குனி" },
];
export const TAMIL_STARS = [
  { label: "அஸ்வினி", value: "அஸ்வினி" },
  { label: "பரணி", value: "பரணி" },
  { label: "கார்த்திகை", value: "கார்த்திகை" },
  { label: "ரோகிணி", value: "ரோகிணி" },
  { label: "மிருகசீரிடம்", value: "மிருகசீரிடம்" },
  { label: "திருவாதிரை", value: "திருவாதிரை" },
  { label: "புனர்பூசம்", value: "புனர்பூசம்" },
  { label: "பூசம்", value: "பூசம்" },
  { label: "ஆயில்யம்", value: "ஆயில்யம்" },
  { label: "மகம்", value: "மகம்" },
  { label: "பூரம்", value: "பூரம்" },
  { label: "உத்திரம்", value: "உத்திரம்" },
  { label: "ஹஸ்தம்", value: "ஹஸ்தம்" },
  { label: "சித்திரை", value: "சித்திரை" },
  { label: "ஸ்வாதி", value: "ஸ்வாதி" },
  { label: "விசாகம்", value: "விசாகம்" },
  { label: "அனுஷம்", value: "அனுஷம்" },
  { label: "கேட்டை", value: "கேட்டை" },
  { label: "மூலம்", value: "மூலம்" },
  { label: "பூராடம்", value: "பூராடம்" },
  { label: "உத்திராடம்", value: "உத்திராடம்" },
  { label: "திருவோணம்", value: "திருவோணம்" },
  { label: "அவிட்டம்", value: "அவிட்டம்" },
  { label: "சதயம்", value: "சதயம்" },
  { label: "பூரட்டாதி", value: "பூரட்டாதி" },
  { label: "உத்திரட்டாதி", value: "உத்திரட்டாதி" },
  { label: "ரேவதி", value: "ரேவதி" },
];
